### ISSUE TITLE
更换主题后出错

### ISSUE THREAD

**Issue by nypxzh** [otale/theme_greyshade#2]
## 更换主题之后出现这种问题,而且样式乱七八糟.大佬,怎么办

```
jetbrick.template.runtime.InterpretException: cannot resolve macro: pageLink

template: themes/theme_greyshade-master/index.html: 24,18
-------------------------------------------------------------------------------
 22:         #end
 23:         <nav class="page-navi">
 24:             #call pageLink('<i class="icon icon-left"></i> 上一页','prev')
                       ^ -- here
 25:             #call pageLink('<i class="icon icon-right"></i> 下一页','next')
 26:         </nav>
-------------------------------------------------------------------------------

        at jetbrick.template.parser.ast.AstDirectiveCall.execute(AstDirectiveCall.java:56)
        at jetbrick.template.parser.ast.AstStatementList.execute(AstStatementList.java:212)
        at jetbrick.template.parser.ast.AstTemplate.execute(AstTemplate.java:37)
        at jetbrick.template.JetTemplateImpl.doInterpret(JetTemplateImpl.java:160)
        at jetbrick.template.JetTemplateImpl.render(JetTemplateImpl.java:141)
        at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:106)
        at com.blade.mvc.http.wrapper.ServletResponse.render(ServletResponse.java:275)
        at com.blade.mvc.view.resolve.RouteViewResolve.handle(RouteViewResolve.java:64)
        at com.blade.mvc.dispatch.DispatcherHandler.routeHandle(DispatcherHandler.java:181)
        at com.blade.mvc.dispatch.DispatcherHandler.handle(DispatcherHandler.java:93)
        at com.blade.mvc.dispatch.DispatcherServlet.service(DispatcherServlet.java:39)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:830)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:564)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:318)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
        at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:745)
[tale] 2017-05-16 04:48:01,975 INFO  [blade-pool-12] com.blade.mvc.dispatch.DispatcherHandler | GET     /templates/themes/theme_greyshade-master/static/css/style.css   HTTP/1.0
[tale] 2017-05-16 04:48:02,146 INFO  [blade-pool-12] com.blade.mvc.dispatch.DispatcherHandler | GET     /templates/themes/theme_greyshade-master/static/images/avatar.png       HTTP/1.0
[tale] 2017-05-16 04:48:02,475 INFO  [blade-pool-12] com.blade.mvc.dispatch.DispatcherHandler | GET     /templates/themes/theme_greyshade-master/static/images/left-bg2.jpg     HTTP/1.0
[tale] 2017-05-16 04:48:02,894 INFO  [blade-pool-12] com.blade.mvc.dispatch.DispatcherHandler | GET     /templates/themes/theme_greyshade-master/static/images/avatar.png       HTTP/1.0
[tale] 2017-05-16 04:48:04,570 INFO  [blade-pool-12] com.blade.mvc.dispatch.DispatcherHandler | GET     /       HTTP/1.0
[tale] 2017-05-16 04:48:04,571 INFO  [blade-pool-12] com.tale.interceptor.BaseInterceptor | UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
[tale] 2017-05-16 04:48:04,571 INFO  [blade-pool-12] com.tale.interceptor.BaseInterceptor | 用户访问地址: /, 来路地址: 183.240.202.10
[tale] 2017-05-16 04:48:04,571 DEBUG [blade-pool-12] org.sql2o.Query | Executing query:
select count(0) from (select allow_comment,allow_feed,allow_ping,author_id,categories,cid,comments_num,content,created,fmt_type,hits,modified,slug,status,tags,thumb_img,title,type from t_contents where type = ? and status = ?) tmp_count
[tale] 2017-05-16 04:48:04,571 DEBUG [blade-pool-12] org.sql2o.Query | Executing query:
select count(0) from (select allow_comment,allow_feed,allow_ping,author_id,categories,cid,comments_num,content,created,fmt_type,hits,modified,slug,status,tags,thumb_img,title,type from t_contents where type = ? and status = ?) tmp_count
[tale] 2017-05-16 04:48:04,572 DEBUG [blade-pool-12] org.sql2o.Query | total: 1 ms; executed scalar [No name]
[tale] 2017-05-16 04:48:04,572 DEBUG [blade-pool-12] org.sql2o.Query | Executing query:
select allow_comment,allow_feed,allow_ping,author_id,categories,cid,comments_num,content,created,fmt_type,hits,modified,slug,status,tags,thumb_img,title,type from t_contents where type = ? and status = ? order by created desc limit 0,12
[tale] 2017-05-16 04:48:04,572 DEBUG [blade-pool-12] org.sql2o.Query | total: 0 ms, execution: 0 ms, reading and parsing: 0 ms; executed [null]
[tale] 2017-05-16 04:48:04,576 ERROR [blade-pool-12] com.blade.mvc.http.wrapper.ServletResponse |
jetbrick.template.runtime.InterpretException: cannot resolve macro: pageLink
```

**Comment by hellokaton** [comment]
你是在哪个版本出的问题？
